// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFk8B9ZDsPk-xwSQfruJKQ1MHbE9lNuU4',
    appId: '1:589996260586:web:82f8e296209d7c76b12b93',
    messagingSenderId: '589996260586',
    projectId: 'food-donation-project-bcbd5',
    authDomain: 'food-donation-project-bcbd5.firebaseapp.com',
    storageBucket: 'food-donation-project-bcbd5.firebasestorage.app',
    measurementId: 'G-5EN33FW7K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnyTu5JHNuCU8v2Dc3YaC-g9LfermakIg',
    appId: '1:589996260586:android:4f7fc256fc328b98b12b93',
    messagingSenderId: '589996260586',
    projectId: 'food-donation-project-bcbd5',
    storageBucket: 'food-donation-project-bcbd5.firebasestorage.app',
  );
}
